#!/bin/sh
# sort a file in Cyrillic koi8-r encoding alphabetically
#
# -f Fold lower case characters into the equivalent upper case
#    characters when sorting so that, for example, `B' is greater
#    than `a' (without `-f', uppercase characters precede lowercase).

if [ "$1" = "-f" ]; then
	FOLD="-f"
	ALPH='áÁâÂ÷×çÇ½­äÄåÅ´¤öÖúÚéÉ¶¦·§êÊëËìÌíÍîÎïÏğĞòÒóÓôÔõÕæÆèÈãÃşŞûÛıİàÀñÑøØ'
else
	ALPH='áâ÷ç½äå´öúé¶·êëìíîïğòóôõæèãşûıàñøÁÂ×Ç­ÄÅ¤ÖÚÉ¦§ÊËÌÍÎÏĞÒÓÔÕÆÈÃŞÛİÀÑØ'
fi
TEMP='§·ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×Ø¦ÚÛ¤İŞ­àáâãäåæçèéêëìíîïğñòóôõö÷ø¶úû´ış½'

tr $ALPH $TEMP | sort $FOLD | tr $TEMP $ALPH
